addons:
  sonarcloud:
    organization: "flowershop"
    token:
      secure: "a65076a82776950cfa734ac1541444e742464df0" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AndriiHorbenko_FlowerShop