addons:
  sonarcloud:
    organization: "flowershop"
    token:
      secure: "5aeced66f58866b64ad6e243826bef2fa2440582" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AndriiHorbenko_FlowerShop